# Generated by Django 3.1.1 on 2020-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(blank=True, null=True, verbose_name='معلم'),
        ),
    ]
