# Generated by Django 3.1.1 on 2020-09-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_school', '0002_auto_20200930_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
    ]
